zuul:
  routes:
    primary:
      url: http://localhost:8081
      sensitive-headers:
    resource:
      url: http://localhost:8082
      sensitive-headers:

security:
  user:
    name: arip
    password: password
    role: USER, ADMIN, READER, WRITER, ACCTUATOR
  sessions: ALWAYS

spring:
  session:
    store-type: redis

logging:
  level:
    org:
      springframework:
        security: DEBUG

