zuul:
  routes:
    primary:
      url: http://localhost:8081
      sensitive-headers:
    resource:
      url: http://localhost:8082
      sensitive-headers:
    admin:
      url: http://localhost:8083
      sensitive-headers:

spring:
  session:
    store-type: redis

logging:
  level:
    org:
      springframework:
        security: DEBUG

