server :
  address : 127.0.0.1
  port : 8081

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/uaa/user

logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE