server :
  address : 127.0.0.1
  port : 8081

security:
  sessions: NEVER

spring:
  session:
    store-type: redis

logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE