security:
  user:
    name: arip
    password: password

spring:
  session:
    store-type: redis

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8081
      sensitive-headers:

logging:
  level:
    org.springframework.security: DEBUG